"""
Input:
- video_interaction_average.parquet (output from get_average_of_video_interactions.py)
- user_temporal_cluster_embeddings.parquet (output from get_temporal_interaction_embedding.py)
- user_video_clusters_distribution.parquet (output from get_user_video_cluster_distribution.py)

Output:
- merged_user_embeddings.parquet (combined user embeddings from all three sources)

This script merges the embeddings generated by different parts of the pipeline to create
a comprehensive embedding vector for each user.
"""

import os
import subprocess
import sys
import pathlib
import subprocess
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import *
import numpy as np

# Initialize Spark Session
spark = SparkSession.builder.appName("Merge Part Embeddings").getOrCreate()

# Define constants
DATA_ROOT = "/home/dataproc/recommendation-engine/data_root"


def merge_part_embeddings(
    video_interaction_path, temporal_embeddings_path, cluster_distribution_path
):
    """
    Joins the three embeddings files and keeps only the embedding columns.

    Args:
        video_interaction_path: Path to video_interaction_average.parquet file
        temporal_embeddings_path: Path to user_temporal_cluster_embeddings.parquet file
        cluster_distribution_path: Path to user_video_clusters_distribution.parquet file

    Returns a dataframe with all embeddings joined by user_id.
    """
    print("STEP 1: Loading input data")

    # Load the three embedding dataframes
    df_video_interaction = spark.read.parquet(video_interaction_path)
    df_temporal_embeddings = spark.read.parquet(temporal_embeddings_path)
    df_cluster_distribution = spark.read.parquet(cluster_distribution_path)

    # Print schema and counts for debugging
    print("Video interaction average count:", df_video_interaction.count())
    df_video_interaction.printSchema()

    print("Temporal embeddings count:", df_temporal_embeddings.count())
    df_temporal_embeddings.printSchema()

    print("Cluster distribution count:", df_cluster_distribution.count())
    df_cluster_distribution.printSchema()

    print("\nSTEP 2: Selecting and renaming embedding columns")

    # Select only the user_id and embeddings from each dataframe with clear names
    df_video_emb = df_video_interaction.select(
        "user_id", F.col("embedding").alias("avg_interaction_embedding")
    )

    df_temporal_emb = df_temporal_embeddings.select(
        "user_id", F.col("temporal_embedding").alias("temporal_embedding")
    )

    df_cluster_emb = df_cluster_distribution.select(
        "user_id", F.col("cluster_distribution").alias("cluster_distribution_embedding")
    )

    print("\nSTEP 3: Joining dataframes on user_id")

    # Join all three dataframes on user_id
    # First join video embeddings with temporal embeddings
    df_joined = df_video_emb.join(df_temporal_emb, on="user_id", how="inner")

    # Then join with cluster distribution embeddings
    df_joined = df_joined.join(df_cluster_emb, on="user_id", how="inner")

    # Count users with all embeddings
    total_users = df_joined.count()
    print(f"Total users with all three embeddings: {total_users}")

    print("\nSTEP 4: Creating final output dataframe")

    # The final dataframe includes all three embedding types
    df_result = df_joined.select(
        "user_id",
        "avg_interaction_embedding",
        "temporal_embedding",
        "cluster_distribution_embedding",
    )

    print("Final result count:", df_result.count())
    return df_result


def main():
    """Main execution function"""
    # Create necessary directories

    # Create local output directory if it doesn't exist
    local_output_dir = f"{DATA_ROOT}/emb_analysis"
    subprocess.call(["mkdir", "-p", local_output_dir])

    # Create hdfs directories, overwriting if they exist
    subprocess.call(["hdfs", "dfs", "-mkdir", "-p", "/tmp/emb_analysis"])

    # Define path variables
    video_interaction_path = "/tmp/emb_analysis/video_interaction_average.parquet"
    temporal_embeddings_path = (
        "/tmp/emb_analysis/user_temporal_cluster_embeddings.parquet"
    )
    cluster_distribution_path = (
        "/tmp/emb_analysis/user_video_clusters_distribution.parquet"
    )

    # Define input file mappings
    input_files = {
        "video_interaction_average.parquet": video_interaction_path,
        "user_temporal_cluster_embeddings.parquet": temporal_embeddings_path,
        "user_video_clusters_distribution.parquet": cluster_distribution_path,
    }

    # Copy input files to HDFS if they don't exist there already
    for local_file, hdfs_path in input_files.items():
        subprocess.call(
            [
                "hdfs",
                "dfs",
                "-put",
                "-f",
                f"{DATA_ROOT}/emb_analysis/{local_file}",
                hdfs_path,
            ]
        )

    # Merge the embeddings
    df_result = merge_part_embeddings(
        video_interaction_path, temporal_embeddings_path, cluster_distribution_path
    )

    # Write results to HDFS
    output_path = "/tmp/emb_analysis/merged_user_embeddings.parquet"
    df_result.write.mode("overwrite").parquet(output_path)

    # Create local output directory if not exists (double-check)
    subprocess.call(["mkdir", "-p", local_output_dir])

    # Copy results back to local filesystem
    subprocess.call(["hdfs", "dfs", "-get", "-f", output_path, local_output_dir])

    # Show a sample of data that was written
    print("\nSample of data written:")
    df_result.show(5)

    print(f"Successfully wrote merged user embeddings to {output_path}")
    print(f"And copied back to {local_output_dir}/merged_user_embeddings.parquet")


if __name__ == "__main__":
    main()
