-- Create and populate a table to store the modified IoU calculation results
-- This table will store the results generated by modified_iou_intermediate_table.sql
-- Create the table if it doesn't exist
CREATE TABLE
    IF NOT EXISTS `jay-dhanwant-experiments.stage_test_tables.modified_iou_candidates` (
        cluster_id INT64 NOT NULL,
        video_id_x STRING NOT NULL,
        user_id_list_min_x ARRAY < STRING >,
        user_id_list_success_x ARRAY < STRING >,
        d INT64,
        cluster_id_y INT64 NOT NULL,
        video_id_y STRING NOT NULL,
        user_id_list_min_y ARRAY < STRING >,
        user_id_list_success_y ARRAY < STRING >,
        den INT64,
        num INT64,
        iou_modified FLOAT64,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    ) CLUSTER BY cluster_id,
    video_id_x,
    video_id_y;