name: Build and deploy recommendation service to Cloud Run

on:
  push:
    branches: [dev, main, master]
  pull_request:
    branches: [dev, main, master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "info"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Image tags"
        required: false
        type: string

env:
  REGION: ${{ secrets.REGION || 'us-central1' }}
  SERVICE_NAME: recommendation-service
  REPOSITORY: recommendation-engine-registry
  IMAGE: recommendation-engine

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Only deploy on push to main/dev, not on PRs
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          # Get project ID from gcloud
          PROJECT_ID=$(gcloud config get-value project)
          REGISTRY="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY"
          IMAGE_NAME="$REGISTRY/$IMAGE"

          echo "Project ID: $PROJECT_ID"
          echo "Registry: $REGISTRY"
          echo "Image Name: $IMAGE_NAME"

          # Build the Docker image
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker build -t $IMAGE_NAME:latest .

          # Push to Artifact Registry
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

          echo "Successfully pushed image: $IMAGE_NAME:${{ github.sha }}"
          echo "Successfully pushed image: $IMAGE_NAME:latest"

          # Export for next step
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run..."

          # Create environment variables file to avoid JSON escaping issues
          cat > env.yaml << EOF
          GCP_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
          DEV_MODE: '${{ secrets.DEV_MODE }}'
          GCP_PROJECT_ID: '${{ secrets.PROJECT_ID }}'
          PROXY_REDIS_HOST: '${{ secrets.PROXY_REDIS_HOST }}'
          PROXY_REDIS_PORT: '${{ secrets.PROXY_REDIS_PORT }}'
          REGION: '${{ secrets.REGION }}'
          SERVICE_REDIS_AUTHKEY: '${{ secrets.SERVICE_REDIS_AUTHKEY }}'
          SERVICE_REDIS_CLUSTER_ENABLED: '${{ secrets.SERVICE_REDIS_CLUSTER_ENABLED }}'
          SERVICE_REDIS_HOST: '${{ secrets.SERVICE_REDIS_HOST }}'
          SERVICE_REDIS_INSTANCE_ID: '${{ secrets.SERVICE_REDIS_INSTANCE_ID }}'
          SERVICE_REDIS_PORT: '${{ secrets.SERVICE_REDIS_PORT }}'
          USE_REDIS_PROXY: '${{ secrets.USE_REDIS_PROXY }}'
          PORT: '8000'
          CLOUD_RUN_DEPLOYMENT: 'true'
          EOF

          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME:${{ github.sha }} \
            --allow-unauthenticated \
            --port 8000 \
            --service-account 749244211103-compute@developer.gserviceaccount.com \
            --concurrency 500 \
            --cpu 4 \
            --memory 4Gi \
            --env-vars-file env.yaml \
            --vpc-connector projects/$PROJECT_ID/locations/$REGION/connectors/vpc-for-redis \
            --vpc-egress private-ranges-only \
            --region $REGION \
            --max-instances 10 \
            --min-instances 0 \
            --platform managed \
            --timeout 300s

          echo "Deployment completed successfully!"

      - name: Get Service URL
        run: |
          SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format="value(status.url)")
          echo "🚀 Service deployed at: $SERVICE_URL"
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV

  # Separate job for PR validation (build only, no deploy)
  validate-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build Docker image (validation only)
        run: |
          PROJECT_ID=$(gcloud config get-value project)
          REGISTRY="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY"
          IMAGE_NAME="$REGISTRY/$IMAGE"

          echo "🔍 Validating Docker build for PR..."
          docker build -t $IMAGE_NAME:pr-${{ github.event.number }} .
          echo "✅ Docker build successful!"
