name: Build and Push Docker Image

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Image tags'
        required: false
        type: string

env:
  REGION: ${{ secrets.GCP_REGION || 'us-central1' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        # Get project ID from gcloud
        PROJECT_ID=$(gcloud config get-value project)
        REGISTRY="$REGION-docker.pkg.dev/$PROJECT_ID/recommendation-engine-registry"
        IMAGE_NAME="$REGISTRY/recommendation-engine"

        echo "Project ID: $PROJECT_ID"
        echo "Registry: $REGISTRY"
        echo "Image Name: $IMAGE_NAME"

        # Build the Docker image
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker build -t $IMAGE_NAME:latest .

        # Push to Artifact Registry
        docker push $IMAGE_NAME:${{ github.sha }}
        docker push $IMAGE_NAME:latest

        echo "Successfully pushed image: $IMAGE_NAME:${{ github.sha }}"
        echo "Successfully pushed image: $IMAGE_NAME:latest"
